### ISSUE TITLE
System.InvalidCastException type Sytem.Object[] to System.String[]

### ISSUE THREAD

**Issue by chrisbbe** [postsharp/PostSharp.Community.Packer#3]
Hi,

By initializing any of the string[] fields in PackerAttribute.cs, Packer throws InvalidCastException when casting from Sytem.Object[] to System.String[].

**Comment by chrisbbe** [comment]
```
[assembly: Packer(Unmanaged32Assemblies = new[] {"Something"})]
```

Will crash.

**Comment by chrisbbe** [comment]
Can you proceed with resolving the build failure and merging the PR for this bug? Thanks.

**Comment by gfraiteur** [comment]
Done.
