### ISSUE TITLE
Compiled program is not actually packed (.NET Framework 4.6.1, 4.7.2, 4.8)

### ISSUE THREAD

**Issue by MHLoppy** [postsharp/PostSharp.Community.Packer#7]
After dancing around with the same issue as #2 (eventually I just gave up and downloaded the standalone; every other method just eventually pointed to the downloads page - even the mentioned exe), I tried building my project in VS2019 Community with `[assembly: Packer]` in the project as per the instructions, and PostSharp does note in the logs that it's alive during that process.

> <project> does not contain any aspect or other transformation.

For legacy reasons the project was initially targeting .NET Framework 4.6.1. The compiled release spewed out every single DLL the project had ever touched (and possibly some that it never touched) into the release folder.

I tried re-targeting to 4.7.2 and then again to 4.8 and a much milder version of the same thing occurred with both versions: extra DLLs were not packed, just dumped into the release folder. In this case the DLLs were limited to the expected DLLs used by the main exe, as well as a few PostSharp-related files. The same message appeared in the output log each time I built/rebuilt.

For good measure I:
- restarted VS twice,
- tried putting `[assembly: Packer]` into a different C# file in the project,
- tried building the project with both the default Debug and Release presets,
- tried adding `using` statements to the relevant file(s),
- tried cleaning the projects,
- tried manually wiping some of the files,
- tried unloading projects with no related references,
- tried straight up removing said projects from the solution,
- tried updating the versions of PostSharp and PostSharp.Redist that Nuget auto-downloaded for PostSharp.Community.Packer (to 6.9.7, from 6.6.6(?)),
- tried poking around the settings for PostSharp

but ended up with a not-packed compiled program regardless of these efforts.

**Comment by addabis** [comment]
I can confirm that all files are copied to the output directory, but at the same time the resulting binary contains all references as resources and runs without them present and I do not get the compilation warning.

Can you share a repro project where this does not happen or at least a diag build log (running msbuild with -v:diag)?

**Comment by MHLoppy** [comment]
Unfortunately I was trying to test different packing solutions (this, .NET core's own, a couple others) pretty quickly; I never committed the code for any of the test runs except for when I had to port to .NET core. However, the code should be similar to this ["maniac2" branch](https://github.com/MHLoppy/CBP-Launcher/tree/maniac2) (the code.. reflects my abilities), with the issue in question affecting CBP-Setup-GUI and CBP-Setup-GUI.Language (the latter being satellite assemblies for language files, set up as per [this SO answer](https://stackoverflow.com/questions/373388/best-way-to-implement-multi-language-globalization-in-large-net-project/35813707#35813707)).

When compiled (without packing) there would be Project.exe (~88KB give or take depending on exactly what I'd coded at the time), then Project.Language.dll (~16KB) at the same level (English strings), and then a two-letter-language-code "de" sub-folder containing a Project.Language.de.dll (~4KB) which contains test strings when running in German. The base folder would also have a couple of .config files.

In making this reply I went back to try to reproduce the problem with the same projects (similar code, not exactly the same). I reproduced successfully but did also manage to compile a packed file by putting the assembly code in `AssemblyInfo.cs` combined with a `using PostSharp.Community.Packer`. Any other place it would compile not-packed (same .exe size and unable to load strings outside of that folder i.e. program can't run), and without the `using` it would fail to compile. I'm not an experienced dev, so perhaps this was just my bad - was that combination supposed to be inferred based on the instruction?

> Add [assembly: Packer] somewhere in your code.

I had assumed I could pop that in anywhere in any of the project's .cs files and it would be okay without additional steps needed.

**Comment by addabis** [comment]
The file in which you put the assembly attribute should not matter as long as it is compiled (PostSharp is looking for the attribute on the assembly, not at source files). You can also use <AssemblyAttribute> item group in your project file if that is supported by the tool chain (not sure if that works with older .NET Framework projects). I'll have a look at your project.

**Comment by addabis** [comment]
So when I add the packer into the project and add the attribute, the CBP-Setup-GUI.exe works without dependencies and everything is packed into the assembly. 

The only problem is that everything gets copied into the output directory, which is a thing that is hard to change. To achieve that, you would need to have some kind of output from PostSharp that notifies a Packer's MSBuild target which libraries were packed so that these can be removed from the item group that governs what is copied to the output.

Are you fine with me closing this ticket?

**Comment by MHLoppy** [comment]
> CBP-Setup-GUI.exe works without dependencies and everything is packed into the assembly.

That unfortunately does not appear to be the case on my end: https://www.youtube.com/watch?v=t8wUCdm7gTc (1 minute, no audio)

**Comment by addabis** [comment]
Frankly, I did not know that you can put `[assembly: SomeAttribute]` into the middle of a class like this :-). The warning is telling you that such an attribute is going to be ignored. 

You need to put that between the last `using` and `namespace` at the beginning of the source file.

**Comment by MHLoppy** [comment]
Hah, okay - that (and an appropriate `using` statement) did the trick. A quick update to the documentation on where it needs to go would be helpful for people like me who have no idea what they're doing :P As I said earlier, I assumed it was scanning for the phrase anywhere regardless of location. Thanks for the help!

(feel free to close the issue at your behest)

**Comment by addabis** [comment]
I have updated the doc. I'm closing the issue.
